name: Mysql Backup
description: |
Backup a data-oriented container and a MariaDB/MySQL container and upload them to a FTP/SFTP server using lftp.
category: Clustering
maintainer: "Edispro"
license: 
projectURL: https://hub.docker.com/r/ambroisemaupate/ftp-backup