.catalog:
  name: "Logstash"
  version: "6.5.1-club21-small"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "collector_inputs"
      description: |
        Logstash collection tier inputs. These will be added
        directly to input { } section of logstash.conf
        jdbc_driver_library path /usr/share/logstash/lib/mysql-connector-java.jar
      label: "Logstash inputs"
      type: "multiline"
      required: true
      default: |
        udp {
          port => 5000
          codec => "json"
        }
    - variable: "indexer_filters"
      description: |
        Logstash indexing tier filters. These will be added
        directly to filter { } section of logstash.conf
      label: "Logstash filters"
      type: "multiline"
      required: false
      default: ""
    - variable: "indexer_outputs"
      description: |
        Logstash indexing tier outputs. These will be added
        directly to output { } section of logstash.conf
      label: "Logstash outputs"
      type: "multiline"
      required: true
      default: |
            stdout {
                codec => rubydebug
                  }
            elasticsearch {
            index => "club21_%{type}"
            document_type => "%{type}"
            hosts => ["elasticsearch.rancher.internal:9200"]
            }
    - variable: "file_path"
      label: "Add Volume to /mnt/logstash"
      default: "/mnt/logstash"
      type: "string"
      required: true
    - variable: "elasticsearch_link"
      description: |
        stack/service link or external service link to elasticsearch
        cluster.
      label: "Elasticsearch stack/service"
      default: ""
      required: true
      type: "service"
    - variable: "mysql_link"
      description: |
        mysql host  mysql.rancher.internal
      label: "mysql stack/service"
      default: ""
      required: true
      type: "service"
    - variable: "mem_limit"
      type: "int"
      required: true
      label: "Memory limit in byte "
      description: "Memory limit in Byte per  container"
      default: 2147483648    
logstash-collector:
  metadata:
    logstash:
      inputs: |
        ${collector_inputs}
      filters: |
        ${indexer_filters}
      outputs: |
        ${indexer_outputs}
