---
.catalog:
  name: "Redis Cluster"
  version: "v4.0.0"
  description: |
    Redis Sentinel Cluster
  questions:
    - variable: REDIS_PASSWORD
      label: "Redis auth password"
      type: password
      required: true
    - variable: REDIS_NODES
      label: Number of redis nodes
      description: Number of Redis server nodes to launch.
      type: int
      default: 3
      required: true
    - variable: SENTINEL_NODES
      label: Number of sentinel nodes
      description: Number of Sentinel nodes to launch.
      type: int
      default: 3
      required: true


version: '2'
services:
  redis-sentinel:
    retain_ip: true
    scale: ${SENTINEL_NODES}
    start_on_create: true
  redis-server:
    retain_ip: true
    scale: ${REDIS_NODES}
    start_on_create: true
