version: '2'
services:
  osync:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    volumes:
    - /root/.ssh:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf}:/etc/osync
    - /etc/localtime:/etc/localtime:ro
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

