version: '2'
services:
  osync:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    volumes:
    - /root/.ssh:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf}:/etc/osync
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_ne: container_name
      io.rancher.scheduler.affinity:host_label_ne: osync=1

