---
.catalog:
  name: "Osync"
  version: "1.3-beta1"
  description: |
    docker-osync
  questions:
    - variable: osync_data
      label: "Data Volume:"
      type: string
      required: true
    - variable: osync_conf
      label: "Config Volume To Server 2:"
      description: "Config For To Server 2"
      type: string
      default: ""
      required: true


version: '2'
services:
  osync:
    scale: 2
    start_on_create: true
