name: Redis Cluster
description: |
  A cluster of Redis instances + Sentinel for High Availability
version: 0.0.1.0-rancher
category: Clustering
maintainer: "Edispro"
minimum_rancher_version: v1.6.0
license: 
projectURL: https://github.com/edispro/Rancher-Catalog