version: '2'
services:
  redis-server:
    image: edispro/redis:5.0.4

    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      REDIS_TIMEOUT: '3600'
    stdin_open: true
    restart: always
    volumes:
    - /mnt/redis:/data
    ports:
    - 6379:6379/tcp
    tty: true
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      redis-server: '1'
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    sysctls:
      net.core.somaxconn: "511"