version: '2'
services:
  osync-main:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always    
    volumes:
    - /root/.ssh:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_2}:/etc/osync
    - /etc/localtime:/etc/localtime:ro
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync-slave
  osync-slave:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always    
    volumes:
    - /root/.ssh:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_1}:/etc/osync
    - /etc/localtime:/etc/localtime:ro
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync-main
