---
.catalog:
  name: "Osync 2 Server"
  version: "1.2"
  description: |
    docker-osync
  questions:
    - variable: osync_data
      label: "Data Volume:"
      type: string
      required: true
    - variable: osync_conf_1
      label: "Config Volume To Server 1:"
      description: "Config For To Server 1"
      type: string
      default: ""
      required: true
    - variable: osync_conf_2
      label: "Config Volume To Server 2:"
      description: "Config For To Server 2"
      type: string
      default: ""
      required: true

version: '2'
services:
  osync-main:
    scale: 1
    start_on_create: true
  osync-slave:
    scale: 1
    start_on_create: true