logstash-collector-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  labels:
    io.rancher.container.hostname_override: container_name
logstash-collector:
  restart: always
  tty: true
  mem_limit: 1073741824
  external_links:
  - ${elasticsearch_link}:elasticsearch
  - ${mysql_link}:mysql
  volumes_from:
  - logstash-collector-config
  volumes:
  - ${file_path}:/mnt/logstash
  command:
  - logstash
  - -f
  - /etc/logstash
  image: edispro/logstash:6.5.1
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-collector-config
    io.rancher.container.hostname_override: container_name
 
