version: '2'
services:
  osync1to2:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_1}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_2}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync3to1,io.rancher.stack_service.name=$${stack_name}/osync4to1
      io.rancher.sidekicks: osync1to3,osync1to4
  osync1to3:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_1}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_3}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync3to1,io.rancher.stack_service.name=$${stack_name}/osync4to1
  osync1to4:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_1}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_4}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync3to1,io.rancher.stack_service.name=$${stack_name}/osync4to1
  osync2to1:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_2}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_1}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to2,io.rancher.stack_service.name=$${stack_name}/osync3to1,io.rancher.stack_service.name=$${stack_name}/osync4to1 
      io.rancher.sidekicks: osync2to3,osync2to4
  osync2to3:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_2}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_3}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to2,io.rancher.stack_service.name=$${stack_name}/osync3to1,io.rancher.stack_service.name=$${stack_name}/osync4to1
  osync2to4:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_2}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_4}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to2,io.rancher.stack_service.name=$${stack_name}/osync3to1,io.rancher.stack_service.name=$${stack_name}/osync4to1   
  osync3to1:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_3}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_1}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to2,io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync4to1
      io.rancher.sidekicks: osync3to2,osync3to4
  osync3to2:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_3}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_2}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to2,io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync4to1
  osync3to4:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_3}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_4}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to2,io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync4to1
  osync4to1:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_4}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_1}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to2,io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync3to1
      io.rancher.sidekicks: osync4to2,osync4to3
  osync4to2:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_4}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_2}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to2,io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync3to1
  osync4to3:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ${osync_ssh_4}:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_3}:/etc/osync
    - /etc/localtime:/etc/localtime:ro    
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/osync1to4,io.rancher.stack_service.name=$${stack_name}/osync2to1,io.rancher.stack_service.name=$${stack_name}/osync3to1

