version: '2'
services:
  osync-main:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    volumes:
    - /root/.ssh:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_1}:/etc/osync
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: osync-salve-1,osync-salve-2
      io.rancher.scheduler.affinity:host_label_ne: osync=1
  osync-salve-1:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    volumes:
    - /root/.ssh:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_2}:/etc/osync
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: osync=2
  osync-salve-2:
    image: edispro/docker-osync:latest
    stdin_open: true
    tty: true
    volumes:
    - /root/.ssh:/root/.ssh
    - ${osync_data}:/data
    - ${osync_conf_3}:/etc/osync
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: osync=3
