---
.catalog:
  name: "Osync For 4 Server"
  version: "1.2"
  description: |
   Osync For 4 Server
   หลังสร้สงแล้ว ให้เข้าไปกด Upgrade แล้วเลือก Scheduling เลือก Run All  containers on a specific host แล้วเลือก server ที่ต้องการจพย้ายไป
  questions:
    - variable: osync_data
      label: "Data Volume:"
      type: string
      required: true
    - variable: osync_conf_1
      label: "Config Volume To Server 1:"
      description: "Config For To Server 1"
      type: string
      default: ""
      required: true
    - variable: osync_conf_2
      label: "Config Volume To Server 2:"
      description: "Config For To Server 2"
      type: string
      default: ""
      required: true
    - variable: osync_conf_3
      label: "Config Volume To Server 3:"
      description: "Config For To Server 3"
      type: string
      default: ""
      required: true
    - variable: osync_conf_4
      label: "Config Volume To Server 4:"
      description: "Config For To Server 4"
      type: string
      default: ""
      required: true
    - variable: osync_ssh_1
      label: "SSH Key Volume To Server 1:"
      description: "SSH Key For To Server 1 ex. /root/.ssh"
      type: string
      default: ""
      required: true
    - variable: osync_ssh_2
      label: "SSH Key Volume To Server 2:"
      description: "SSH Key For To Server 2 ex. /root/.ssh"
      type: string
      default: ""
      required: true 
    - variable: osync_ssh_3
      label: "SSH Key Volume To Server 3:"
      description: "SSH Key For To Server 3 ex. /root/.ssh"
      type: string
      default: ""
      required: true 
    - variable: osync_ssh_4
      label: "SSH Key Volume To Server 4:"
      description: "SSH Key For To Server 4 ex. /root/.ssh"
      type: string
      default: ""
      required: true                         
version: '2'
services:
  osync1to2:
    scale: 1
    start_on_create: true
  osync1to3:
    scale: 1
    start_on_create: true
  osync1to4:
    scale: 1
    start_on_create: true
  osync2to1:
    scale: 1
    start_on_create: true
  osync2to3:
    scale: 1
    start_on_create: true
  osync2to4:
    scale: 1
    start_on_create: true
  osync3to1:
    scale: 1
    start_on_create: true
  osync3to2:
    scale: 1
    start_on_create: true
  osync3to4:
    scale: 1
    start_on_create: true        
  osync4to1:
    scale: 1
    start_on_create: true
  osync4to2:
    scale: 1
    start_on_create: true
  osync4to3:
    scale: 1
    start_on_create: true