version: '2'
services:
  mysqlbackup:
    image: ambroisemaupate/ftp-backup:latest
    stdin_open: true
    tty: true
    restart: always                                       
    volumes:
    - /etc/localtime:/etc/localtime:ro
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

