version: '2'
services:
  osync:
    image: ambroisemaupate/ftp-backup:latest
    stdin_open: true
    tty: true
    restart: always 
    environment:
    - "DB_USER=${DB_USER}"
    - "DB_HOST=${DB_HOST}"
    - "DB_PASS=${DB_PASS}" 
    - "DB_NAME=${DB_NAME}" 
    - "FTP_USER=${FTP_USER}" 
    - "FTP_PASS=${FTP_PASS}" 
    - "FTP_HOST=${FTP_HOST}"
    - "FTP_PORT=${FTP_PORT}"
    - "FTP_PROTO=${FTP_PROTO}"
    - "REMOTE_PATH=${REMOTE_PATH}"                                        
    volumes:
    - /etc/localtime:/etc/localtime:ro
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

