---
.catalog:
  name: "Mysql Backup"
  version: "1"
  description: |
  Backup a data-oriented container and a MariaDB/MySQL container and upload them to a FTP/SFTP server using lftp.

                                    
version: '2'
services:
  osync:
    scale: 1
    start_on_create: true
