name: Osync
description: |
  The docker-osync is based on the osync tool, you can use it to synchronize files between two servers
category: Clustering
maintainer: "Edispro"
minimum_rancher_version: v1.6.0
license: 
projectURL: https://github.com/edispro/docker-osync